title: "RJCP on Github"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: true
logo: "/assets/images/rjcp.png"
footer_content: "RJCP. <a href=\'https://github.com/rjcp/'>Github Repository</a>"